### ISSUE TITLE
Unclear dependency

### ISSUE THREAD

**Issue by Supermatt01** [ZDisket/TensorVox#15]
Hello. I am running this app on win 11 but it keeps crashing when I use it. The project page does not seem to say that it requires Anaconda. Does it need Anaconda to run or not? I would ask on Discord but I have had bad experiences on Discord and no longer use it.

**Comment by ZDisket** [comment]
This isn't a Python app, there are zero lines of Python (well, except for the G2P model trainer), so it shouldn't need Anaconda. What is the error when you use it?

**Comment by Supermatt01** [comment]
So, I try to run it and it won't load a voice and then when I push some of the feature buttons to closes. I am using a nvidia GPU but it might not be running off of the GPU as I have two and forgot to check that. Clicking random text causes it to crash. Clicking infer crashes it. I will try making sure it is running off the right GPU and report back what happens.
