### ISSUE TITLE
Problem with repeating last bit

### ISSUE THREAD

**Issue by aschmitz13** [ZDisket/TensorVox#17]
Hi,

i used LJSpeach DDC as model, set for testing the word-aware max count to 20. But in some sentences it starts repeating the last bit forever, like two-oo-woo-woo-woo-woo. the attention raised to maximum. perhaps that is the issue?

Thank you for any help.

**Comment by ZDisket** [comment]
Very late reply, I was dealing with something. 
LJSpeech DDC model is kinda finicky and made mainly to demonstrate Coqui (converted from Tensorflow) ability. It lacks a stop token which might be an issue.
