### ISSUE TITLE
use c++ to load tflite model

### ISSUE THREAD

**Issue by unparalleled-ysj** [ZDisket/TensorVox#3]
Hello, I would like to ask how to use C++ to load fastspeech2 tflite format model, can you recommend any examples?

**Comment by ZDisket** [comment]
@unparalleled-ysj At first I tried using TFLite for the models, but you need the Flex delegate, at which point you might just use full Tensorflow. 
Here's the very rough code I used before abandoning it.
[TfLiteTest.zip](https://github.com/ZDisket/TensorVox/files/5703433/TfLiteTest.zip)
