### ISSUE TITLE
G2P model fails and crashes with words exceeding 23 characters.

### ISSUE THREAD

**Issue by OscarVanL** [ZDisket/TensorVox#4]
Hi!

I'm trying to re-implement your G2P model in Android and Java in TensorFlow Lite. While doing this I noticed that if I gave inputs greater than 23 characters long, the TensorFlow interpreter failed with the error:

`RuntimeError: Fill dimensions must be >= 0Node number 3 (FILL) failed to invoke.`

For example, this input does **not crash** the application: abcdefghijklmnopqrstuvw (23 chars), but this input **does**: abcdefghijklmnopqrstuvwx (24 chars).

I tried this out inside this TensorVox application, and could reproduce the same crash within your program too, so I do not think it is a mistake I have made. See this video:

https://user-images.githubusercontent.com/7999692/107827010-d5308b00-6d7d-11eb-87de-4fc27f17b41d.mp4

Of course, no real words are 24 characters long (some locations are though!), but we should probably both sanitise our inputs to avoid this, or maybe this is unintended behaviour from your model? :)

**Comment by ZDisket** [comment]
That's unintended but not surprising behavior from the model. Since it isn't a real problem I will just make it so that words longer than 23 chars are ignored.
Thank you for letting me know.

**Comment by OscarVanL** [comment]
That was what I was going to do :)
