### ISSUE TITLE
Batch Inference on C++ 

### ISSUE THREAD

**Issue by zhangsanfeng86** [ZDisket/TensorVox#6]
Hi @ZDisket ，
Thanks for your great work.
For fastspeech2 and tacotron , it's easy batch inference on Python version.
How to batch inference on C++ version.

**Comment by ZDisket** [comment]
@zhangsanfeng86 In this program? You can turn on multi-threaded inference and split by lines, and split your inputs with newlines and insert them into the text box. Then you can Shift + click on the Export All as WAV button.
I've extensively used it for batch inference of repetitive sounds.

**Comment by zhangsanfeng86** [comment]
@ZDisket 
Thanks for the quick reply!
On multi-threaded inference mode, for example: split inputs into three lines. The three lines are different.
Then, three wavs inference at the same time.
my confusion is:  share the same fastspeech2 model  or  use three fastspeech2 models?

**Comment by ZDisket** [comment]
@zhangsanfeng86 They all use the same model and instance, otherwise you'd see memory usage skyrocket.

**Comment by zhangsanfeng86** [comment]
@ZDisket 
OK，thank you！！！
