### ISSUE TITLE
AddressSanitizer:DEADLYSIGNAL

### ISSUE THREAD

**Issue by zhangsanfeng86** [ZDisket/TensorVox#7]
Hi @ZDisket ,
AddressSanitizer check the programme, get warning information as follow:
![image](https://user-images.githubusercontent.com/73547638/128104695-4e0bb385-d4bb-4ea7-9525-2c83481e4c48.png)

**Comment by ZDisket** [comment]
That's Tensorflow related. All I could do was give it a try catch block because it happens on exit, so the operating system frees all resources anyways.

**Comment by zhangsanfeng86** [comment]
ok, thanks
